apiVersion: v1
kind: Service
metadata:
  name: logo-app
  labels:
    app: logo-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 3001
  selector:
    app: netflix-app
